

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBlock;
                ref class ProgressRing;
                ref class Button;
            }
        }
    }
}

namespace IntegrationTestsApp_WinRT
{
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pageTitle;
        private: ::Windows::UI::Xaml::Controls::ProgressRing^ waitingRing;
        private: ::Windows::UI::Xaml::Controls::Button^ runButton;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ mainTextBlock;
    };
}

