
// File generated by Wsutil Compiler version 1.0098 
#include <WebServices.h>
#include "calculator.wsdl.h"

typedef struct _calculator_wsdlLocalDefinitions 
{
    struct  // global types
    {
        char unused;
        struct  // MultipurposeSingleIntegerResponse
        {
            WS_FIELD_DESCRIPTION result;
            WS_FIELD_DESCRIPTION* MultipurposeSingleIntegerResponseFields [1]; 
        } MultipurposeSingleIntegerResponsedescs; // end of MultipurposeSingleIntegerResponse
        struct  // BinaryOpRequest
        {
            WS_FIELD_DESCRIPTION first;
            WS_FIELD_DESCRIPTION second;
            WS_FIELD_DESCRIPTION* BinaryOpRequestFields [2]; 
        } BinaryOpRequestdescs; // end of BinaryOpRequest
        struct  // OperationResponse
        {
            WS_FIELD_DESCRIPTION result;
            WS_FIELD_DESCRIPTION* OperationResponseFields [1]; 
        } OperationResponsedescs; // end of OperationResponse
    } globalTypes;  // end of global types
    struct  // messages
    {
        WS_MESSAGE_DESCRIPTION AdditionRequestMessage;
        WS_MESSAGE_DESCRIPTION AdditionResponseMessage;
        WS_MESSAGE_DESCRIPTION MultiplicationRequestMessage;
        WS_MESSAGE_DESCRIPTION MultiplicationResponseMessage;
        WS_MESSAGE_DESCRIPTION CloseServiceRequestMessage;
        WS_MESSAGE_DESCRIPTION CloseServiceResponseMessage;
    } messages;  // end of messages
    struct  // contracts
    {
        struct  // CalcBindingHeaderAuthSSL
        {
            struct  // CalcBindingHeaderAuthSSL_Add
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION CalcBindingHeaderAuthSSL_Add;
            } CalcBindingHeaderAuthSSL_Add;
            struct  // CalcBindingHeaderAuthSSL_Multiply
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION CalcBindingHeaderAuthSSL_Multiply;
            } CalcBindingHeaderAuthSSL_Multiply;
            struct  // CalcBindingHeaderAuthSSL_CloseService
            {
                WS_PARAMETER_DESCRIPTION params[1];
                WS_OPERATION_DESCRIPTION CalcBindingHeaderAuthSSL_CloseService;
            } CalcBindingHeaderAuthSSL_CloseService;
            WS_OPERATION_DESCRIPTION* operations[3];
            WS_CONTRACT_DESCRIPTION contractDesc;
        } CalcBindingHeaderAuthSSL;
        struct  // CalcBindingSSL
        {
            struct  // CalcBindingSSL_Add
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION CalcBindingSSL_Add;
            } CalcBindingSSL_Add;
            struct  // CalcBindingSSL_Multiply
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION CalcBindingSSL_Multiply;
            } CalcBindingSSL_Multiply;
            struct  // CalcBindingSSL_CloseService
            {
                WS_PARAMETER_DESCRIPTION params[1];
                WS_OPERATION_DESCRIPTION CalcBindingSSL_CloseService;
            } CalcBindingSSL_CloseService;
            WS_OPERATION_DESCRIPTION* operations[3];
            WS_CONTRACT_DESCRIPTION contractDesc;
        } CalcBindingSSL;
        struct  // CalcBindingUnsecure
        {
            struct  // CalcBindingUnsecure_Add
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION CalcBindingUnsecure_Add;
            } CalcBindingUnsecure_Add;
            struct  // CalcBindingUnsecure_Multiply
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION CalcBindingUnsecure_Multiply;
            } CalcBindingUnsecure_Multiply;
            struct  // CalcBindingUnsecure_CloseService
            {
                WS_PARAMETER_DESCRIPTION params[1];
                WS_OPERATION_DESCRIPTION CalcBindingUnsecure_CloseService;
            } CalcBindingUnsecure_CloseService;
            WS_OPERATION_DESCRIPTION* operations[3];
            WS_CONTRACT_DESCRIPTION contractDesc;
        } CalcBindingUnsecure;
    } contracts;  // endof contracts 
    struct  // policies
    {
        struct  // CalcBindingHeaderAuthSSL
        {
            WS_ENCODING encoding;
            WS_ADDRESSING_VERSION addressingVersion;
            WS_ENVELOPE_VERSION envelopeVersion;
            WS_CHANNEL_PROPERTY channelPropertiesArray[3];
            WS_PROTECTION_LEVEL protectionLevel;
            WS_SECURITY_PROPERTY securityPropertiesArray[1];
            struct // headerAuthBinding
            {
                ULONG headerAuthentication;
                WS_SECURITY_BINDING_PROPERTY securityBindingProperties[1];
            } headerAuthBinding; 
        } CalcBindingHeaderAuthSSL;
        struct  // CalcBindingSSL
        {
            WS_ENCODING encoding;
            WS_ADDRESSING_VERSION addressingVersion;
            WS_ENVELOPE_VERSION envelopeVersion;
            WS_CHANNEL_PROPERTY channelPropertiesArray[3];
            WS_PROTECTION_LEVEL protectionLevel;
            WS_SECURITY_PROPERTY securityPropertiesArray[1];
        } CalcBindingSSL;
        struct  // CalcBindingUnsecure
        {
            WS_ENCODING encoding;
            WS_ADDRESSING_VERSION addressingVersion;
            WS_ENVELOPE_VERSION envelopeVersion;
            WS_CHANNEL_PROPERTY channelPropertiesArray[3];
        } CalcBindingUnsecure;
    } policies;
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING EmptyRequestTypeName;  // EmptyRequest
            WS_XML_STRING EmptyRequestTypeNamespace;  // http://calculator.example.org/
            WS_XML_STRING MultipurposeSingleIntegerResponseTypeName;  // MultipurposeSingleIntegerResponse
            WS_XML_STRING MultipurposeSingleIntegerResponseresultLocalName;  // result
            WS_XML_STRING BinaryOpRequestTypeName;  // BinaryOpRequest
            WS_XML_STRING BinaryOpRequestfirstLocalName;  // first
            WS_XML_STRING BinaryOpRequestsecondLocalName;  // second
            WS_XML_STRING OperationResponseTypeName;  // OperationResponse
            WS_XML_STRING CloseServiceRequestTypeName;  // CloseServiceRequest
            WS_XML_STRING CloseServiceResponseTypeName;  // CloseServiceResponse
            WS_XML_STRING AdditionRequestTypeName;  // AdditionRequest
            WS_XML_STRING AdditionResponseTypeName;  // AdditionResponse
            WS_XML_STRING MultiplicationRequestTypeName;  // MultiplicationRequest
            WS_XML_STRING MultiplicationResponseTypeName;  // MultiplicationResponse
            WS_XML_STRING AdditionRequestMessageactionName;  // http://calculator.example.org/Add
            WS_XML_STRING MultiplicationRequestMessageactionName;  // http://calculator.example.org/Multiply
            WS_XML_STRING CloseServiceRequestMessageactionName;  // http://calculator.example.org/Close
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _calculator_wsdlLocalDefinitions;


typedef struct CalcBindingHeaderAuthSSL_AddParamStruct 
{
    double* first;
    double* second;
    double* result;
} CalcBindingHeaderAuthSSL_AddParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK CalcBindingHeaderAuthSSL_AddOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    CalcBindingHeaderAuthSSL_AddCallback _operation = (CalcBindingHeaderAuthSSL_AddCallback)_callback;
    CalcBindingHeaderAuthSSL_AddParamStruct *_stack =(CalcBindingHeaderAuthSSL_AddParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->first),
        *(_stack->second),
        (_stack->result),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct CalcBindingHeaderAuthSSL_MultiplyParamStruct 
{
    double* first;
    double* second;
    double* result;
} CalcBindingHeaderAuthSSL_MultiplyParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK CalcBindingHeaderAuthSSL_MultiplyOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    CalcBindingHeaderAuthSSL_MultiplyCallback _operation = (CalcBindingHeaderAuthSSL_MultiplyCallback)_callback;
    CalcBindingHeaderAuthSSL_MultiplyParamStruct *_stack =(CalcBindingHeaderAuthSSL_MultiplyParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->first),
        *(_stack->second),
        (_stack->result),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct CalcBindingHeaderAuthSSL_CloseServiceParamStruct 
{
    __int64* result;
} CalcBindingHeaderAuthSSL_CloseServiceParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK CalcBindingHeaderAuthSSL_CloseServiceOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    CalcBindingHeaderAuthSSL_CloseServiceCallback _operation = (CalcBindingHeaderAuthSSL_CloseServiceCallback)_callback;
    CalcBindingHeaderAuthSSL_CloseServiceParamStruct *_stack =(CalcBindingHeaderAuthSSL_CloseServiceParamStruct*)_stackStruct;
    return _operation( 
        _context,
        (_stack->result),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct CalcBindingSSL_AddParamStruct 
{
    double* first;
    double* second;
    double* result;
} CalcBindingSSL_AddParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK CalcBindingSSL_AddOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    CalcBindingSSL_AddCallback _operation = (CalcBindingSSL_AddCallback)_callback;
    CalcBindingSSL_AddParamStruct *_stack =(CalcBindingSSL_AddParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->first),
        *(_stack->second),
        (_stack->result),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct CalcBindingSSL_MultiplyParamStruct 
{
    double* first;
    double* second;
    double* result;
} CalcBindingSSL_MultiplyParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK CalcBindingSSL_MultiplyOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    CalcBindingSSL_MultiplyCallback _operation = (CalcBindingSSL_MultiplyCallback)_callback;
    CalcBindingSSL_MultiplyParamStruct *_stack =(CalcBindingSSL_MultiplyParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->first),
        *(_stack->second),
        (_stack->result),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct CalcBindingSSL_CloseServiceParamStruct 
{
    __int64* result;
} CalcBindingSSL_CloseServiceParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK CalcBindingSSL_CloseServiceOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    CalcBindingSSL_CloseServiceCallback _operation = (CalcBindingSSL_CloseServiceCallback)_callback;
    CalcBindingSSL_CloseServiceParamStruct *_stack =(CalcBindingSSL_CloseServiceParamStruct*)_stackStruct;
    return _operation( 
        _context,
        (_stack->result),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct CalcBindingUnsecure_AddParamStruct 
{
    double* first;
    double* second;
    double* result;
} CalcBindingUnsecure_AddParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK CalcBindingUnsecure_AddOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    CalcBindingUnsecure_AddCallback _operation = (CalcBindingUnsecure_AddCallback)_callback;
    CalcBindingUnsecure_AddParamStruct *_stack =(CalcBindingUnsecure_AddParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->first),
        *(_stack->second),
        (_stack->result),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct CalcBindingUnsecure_MultiplyParamStruct 
{
    double* first;
    double* second;
    double* result;
} CalcBindingUnsecure_MultiplyParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK CalcBindingUnsecure_MultiplyOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    CalcBindingUnsecure_MultiplyCallback _operation = (CalcBindingUnsecure_MultiplyCallback)_callback;
    CalcBindingUnsecure_MultiplyParamStruct *_stack =(CalcBindingUnsecure_MultiplyParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->first),
        *(_stack->second),
        (_stack->result),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct CalcBindingUnsecure_CloseServiceParamStruct 
{
    __int64* result;
} CalcBindingUnsecure_CloseServiceParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK CalcBindingUnsecure_CloseServiceOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    CalcBindingUnsecure_CloseServiceCallback _operation = (CalcBindingUnsecure_CloseServiceCallback)_callback;
    CalcBindingUnsecure_CloseServiceParamStruct *_stack =(CalcBindingUnsecure_CloseServiceParamStruct*)_stackStruct;
    return _operation( 
        _context,
        (_stack->result),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif
const static _calculator_wsdlLocalDefinitions calculator_wsdlLocalDefinitions =
{
    { // global types
        0,
        {  // MultipurposeSingleIntegerResponse
            {  // field description for result
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.MultipurposeSingleIntegerResponseresultLocalName, // result
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.EmptyRequestTypeNamespace, // http://calculator.example.org/
            WS_INT64_TYPE,
            0,
            WsOffsetOf(MultipurposeSingleIntegerResponse, result),
            0,
            0,
            0xffffffff
            },    // end of field description for result
            {  // fields description for MultipurposeSingleIntegerResponse
            (WS_FIELD_DESCRIPTION*)&calculator_wsdlLocalDefinitions.globalTypes.MultipurposeSingleIntegerResponsedescs.result,
            },
        },    // MultipurposeSingleIntegerResponse
        {  // BinaryOpRequest
            {  // field description for first
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestfirstLocalName, // first
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.EmptyRequestTypeNamespace, // http://calculator.example.org/
            WS_DOUBLE_TYPE,
            0,
            WsOffsetOf(BinaryOpRequest, first),
            0,
            0,
            0xffffffff
            },    // end of field description for first
            {  // field description for second
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestsecondLocalName, // second
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.EmptyRequestTypeNamespace, // http://calculator.example.org/
            WS_DOUBLE_TYPE,
            0,
            WsOffsetOf(BinaryOpRequest, second),
            0,
            0,
            0xffffffff
            },    // end of field description for second
            {  // fields description for BinaryOpRequest
            (WS_FIELD_DESCRIPTION*)&calculator_wsdlLocalDefinitions.globalTypes.BinaryOpRequestdescs.first,
            (WS_FIELD_DESCRIPTION*)&calculator_wsdlLocalDefinitions.globalTypes.BinaryOpRequestdescs.second,
            },
        },    // BinaryOpRequest
        {  // OperationResponse
            {  // field description for result
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.MultipurposeSingleIntegerResponseresultLocalName, // result
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.EmptyRequestTypeNamespace, // http://calculator.example.org/
            WS_DOUBLE_TYPE,
            0,
            WsOffsetOf(OperationResponse, result),
            0,
            0,
            0xffffffff
            },    // end of field description for result
            {  // fields description for OperationResponse
            (WS_FIELD_DESCRIPTION*)&calculator_wsdlLocalDefinitions.globalTypes.OperationResponsedescs.result,
            },
        },    // OperationResponse
    }, // end of global types
    {  // messages
        {  // message description for AdditionRequestMessage
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.AdditionRequestMessageactionName, // http://calculator.example.org/Add
            (WS_ELEMENT_DESCRIPTION*)&calculator_wsdl.globalElements.AdditionRequest, 
        },    // message description for AdditionRequestMessage
        {  // message description for AdditionResponseMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&calculator_wsdl.globalElements.AdditionResponse, 
        },    // message description for AdditionResponseMessage
        {  // message description for MultiplicationRequestMessage
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.MultiplicationRequestMessageactionName, // http://calculator.example.org/Multiply
            (WS_ELEMENT_DESCRIPTION*)&calculator_wsdl.globalElements.MultiplicationRequest, 
        },    // message description for MultiplicationRequestMessage
        {  // message description for MultiplicationResponseMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&calculator_wsdl.globalElements.MultiplicationResponse, 
        },    // message description for MultiplicationResponseMessage
        {  // message description for CloseServiceRequestMessage
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.CloseServiceRequestMessageactionName, // http://calculator.example.org/Close
            (WS_ELEMENT_DESCRIPTION*)&calculator_wsdl.globalElements.CloseServiceRequest, 
        },    // message description for CloseServiceRequestMessage
        {  // message description for CloseServiceResponseMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&calculator_wsdl.globalElements.CloseServiceResponse, 
        },    // message description for CloseServiceResponseMessage
    },  // end of messages 
    {  // contracts
        {  // CalcBindingHeaderAuthSSL,
            {  // CalcBindingHeaderAuthSSL_Add
                {  // parameter descriptions for CalcBindingHeaderAuthSSL_Add
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for CalcBindingHeaderAuthSSL_Add
                {  // operation description for CalcBindingHeaderAuthSSL_Add
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.AdditionRequestMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.AdditionResponseMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)calculator_wsdlLocalDefinitions.contracts.CalcBindingHeaderAuthSSL.CalcBindingHeaderAuthSSL_Add.params,
                    CalcBindingHeaderAuthSSL_AddOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for CalcBindingHeaderAuthSSL_Add
            },  // CalcBindingHeaderAuthSSL_Add
            {  // CalcBindingHeaderAuthSSL_Multiply
                {  // parameter descriptions for CalcBindingHeaderAuthSSL_Multiply
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for CalcBindingHeaderAuthSSL_Multiply
                {  // operation description for CalcBindingHeaderAuthSSL_Multiply
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.MultiplicationRequestMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.MultiplicationResponseMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)calculator_wsdlLocalDefinitions.contracts.CalcBindingHeaderAuthSSL.CalcBindingHeaderAuthSSL_Multiply.params,
                    CalcBindingHeaderAuthSSL_MultiplyOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for CalcBindingHeaderAuthSSL_Multiply
            },  // CalcBindingHeaderAuthSSL_Multiply
            {  // CalcBindingHeaderAuthSSL_CloseService
                {  // parameter descriptions for CalcBindingHeaderAuthSSL_CloseService
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for CalcBindingHeaderAuthSSL_CloseService
                {  // operation description for CalcBindingHeaderAuthSSL_CloseService
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.CloseServiceRequestMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.CloseServiceResponseMessage, 
                    0,
                    0,
                    1,
                    (WS_PARAMETER_DESCRIPTION*)calculator_wsdlLocalDefinitions.contracts.CalcBindingHeaderAuthSSL.CalcBindingHeaderAuthSSL_CloseService.params,
                    CalcBindingHeaderAuthSSL_CloseServiceOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for CalcBindingHeaderAuthSSL_CloseService
            },  // CalcBindingHeaderAuthSSL_CloseService
            {  // array of operations for CalcBindingHeaderAuthSSL
                (WS_OPERATION_DESCRIPTION*)&calculator_wsdlLocalDefinitions.contracts.CalcBindingHeaderAuthSSL.CalcBindingHeaderAuthSSL_Add.CalcBindingHeaderAuthSSL_Add,
                (WS_OPERATION_DESCRIPTION*)&calculator_wsdlLocalDefinitions.contracts.CalcBindingHeaderAuthSSL.CalcBindingHeaderAuthSSL_Multiply.CalcBindingHeaderAuthSSL_Multiply,
                (WS_OPERATION_DESCRIPTION*)&calculator_wsdlLocalDefinitions.contracts.CalcBindingHeaderAuthSSL.CalcBindingHeaderAuthSSL_CloseService.CalcBindingHeaderAuthSSL_CloseService,
            },  // array of operations for CalcBindingHeaderAuthSSL
            {  // contract description for CalcBindingHeaderAuthSSL
            3,
            (WS_OPERATION_DESCRIPTION**)calculator_wsdlLocalDefinitions.contracts.CalcBindingHeaderAuthSSL.operations,
            },  // end of contract description for CalcBindingHeaderAuthSSL
        },  // CalcBindingHeaderAuthSSL
        {  // CalcBindingSSL,
            {  // CalcBindingSSL_Add
                {  // parameter descriptions for CalcBindingSSL_Add
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for CalcBindingSSL_Add
                {  // operation description for CalcBindingSSL_Add
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.AdditionRequestMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.AdditionResponseMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)calculator_wsdlLocalDefinitions.contracts.CalcBindingSSL.CalcBindingSSL_Add.params,
                    CalcBindingSSL_AddOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for CalcBindingSSL_Add
            },  // CalcBindingSSL_Add
            {  // CalcBindingSSL_Multiply
                {  // parameter descriptions for CalcBindingSSL_Multiply
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for CalcBindingSSL_Multiply
                {  // operation description for CalcBindingSSL_Multiply
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.MultiplicationRequestMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.MultiplicationResponseMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)calculator_wsdlLocalDefinitions.contracts.CalcBindingSSL.CalcBindingSSL_Multiply.params,
                    CalcBindingSSL_MultiplyOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for CalcBindingSSL_Multiply
            },  // CalcBindingSSL_Multiply
            {  // CalcBindingSSL_CloseService
                {  // parameter descriptions for CalcBindingSSL_CloseService
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for CalcBindingSSL_CloseService
                {  // operation description for CalcBindingSSL_CloseService
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.CloseServiceRequestMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.CloseServiceResponseMessage, 
                    0,
                    0,
                    1,
                    (WS_PARAMETER_DESCRIPTION*)calculator_wsdlLocalDefinitions.contracts.CalcBindingSSL.CalcBindingSSL_CloseService.params,
                    CalcBindingSSL_CloseServiceOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for CalcBindingSSL_CloseService
            },  // CalcBindingSSL_CloseService
            {  // array of operations for CalcBindingSSL
                (WS_OPERATION_DESCRIPTION*)&calculator_wsdlLocalDefinitions.contracts.CalcBindingSSL.CalcBindingSSL_Add.CalcBindingSSL_Add,
                (WS_OPERATION_DESCRIPTION*)&calculator_wsdlLocalDefinitions.contracts.CalcBindingSSL.CalcBindingSSL_Multiply.CalcBindingSSL_Multiply,
                (WS_OPERATION_DESCRIPTION*)&calculator_wsdlLocalDefinitions.contracts.CalcBindingSSL.CalcBindingSSL_CloseService.CalcBindingSSL_CloseService,
            },  // array of operations for CalcBindingSSL
            {  // contract description for CalcBindingSSL
            3,
            (WS_OPERATION_DESCRIPTION**)calculator_wsdlLocalDefinitions.contracts.CalcBindingSSL.operations,
            },  // end of contract description for CalcBindingSSL
        },  // CalcBindingSSL
        {  // CalcBindingUnsecure,
            {  // CalcBindingUnsecure_Add
                {  // parameter descriptions for CalcBindingUnsecure_Add
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for CalcBindingUnsecure_Add
                {  // operation description for CalcBindingUnsecure_Add
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.AdditionRequestMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.AdditionResponseMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)calculator_wsdlLocalDefinitions.contracts.CalcBindingUnsecure.CalcBindingUnsecure_Add.params,
                    CalcBindingUnsecure_AddOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for CalcBindingUnsecure_Add
            },  // CalcBindingUnsecure_Add
            {  // CalcBindingUnsecure_Multiply
                {  // parameter descriptions for CalcBindingUnsecure_Multiply
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for CalcBindingUnsecure_Multiply
                {  // operation description for CalcBindingUnsecure_Multiply
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.MultiplicationRequestMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.MultiplicationResponseMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)calculator_wsdlLocalDefinitions.contracts.CalcBindingUnsecure.CalcBindingUnsecure_Multiply.params,
                    CalcBindingUnsecure_MultiplyOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for CalcBindingUnsecure_Multiply
            },  // CalcBindingUnsecure_Multiply
            {  // CalcBindingUnsecure_CloseService
                {  // parameter descriptions for CalcBindingUnsecure_CloseService
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for CalcBindingUnsecure_CloseService
                {  // operation description for CalcBindingUnsecure_CloseService
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.CloseServiceRequestMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.CloseServiceResponseMessage, 
                    0,
                    0,
                    1,
                    (WS_PARAMETER_DESCRIPTION*)calculator_wsdlLocalDefinitions.contracts.CalcBindingUnsecure.CalcBindingUnsecure_CloseService.params,
                    CalcBindingUnsecure_CloseServiceOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for CalcBindingUnsecure_CloseService
            },  // CalcBindingUnsecure_CloseService
            {  // array of operations for CalcBindingUnsecure
                (WS_OPERATION_DESCRIPTION*)&calculator_wsdlLocalDefinitions.contracts.CalcBindingUnsecure.CalcBindingUnsecure_Add.CalcBindingUnsecure_Add,
                (WS_OPERATION_DESCRIPTION*)&calculator_wsdlLocalDefinitions.contracts.CalcBindingUnsecure.CalcBindingUnsecure_Multiply.CalcBindingUnsecure_Multiply,
                (WS_OPERATION_DESCRIPTION*)&calculator_wsdlLocalDefinitions.contracts.CalcBindingUnsecure.CalcBindingUnsecure_CloseService.CalcBindingUnsecure_CloseService,
            },  // array of operations for CalcBindingUnsecure
            {  // contract description for CalcBindingUnsecure
            3,
            (WS_OPERATION_DESCRIPTION**)calculator_wsdlLocalDefinitions.contracts.CalcBindingUnsecure.operations,
            },  // end of contract description for CalcBindingUnsecure
        },  // CalcBindingUnsecure
    },  // end of contracts 
    {  // policies
        {
            WS_ENCODING_XML_UTF8,
            WS_ADDRESSING_VERSION_TRANSPORT,
            WS_ENVELOPE_VERSION_SOAP_1_2,
            { // channelPropertiesArray
                {
                    WS_CHANNEL_PROPERTY_ENCODING,
                    (void*)&calculator_wsdlLocalDefinitions.policies.CalcBindingHeaderAuthSSL.encoding,
                    sizeof(calculator_wsdlLocalDefinitions.policies.CalcBindingHeaderAuthSSL.encoding),
                },
                {
                    WS_CHANNEL_PROPERTY_ADDRESSING_VERSION,
                    (void*)&calculator_wsdlLocalDefinitions.policies.CalcBindingHeaderAuthSSL.addressingVersion,
                    sizeof(calculator_wsdlLocalDefinitions.policies.CalcBindingHeaderAuthSSL.addressingVersion),
                },
                {
                    WS_CHANNEL_PROPERTY_ENVELOPE_VERSION,
                    (void*)&calculator_wsdlLocalDefinitions.policies.CalcBindingHeaderAuthSSL.envelopeVersion,
                    sizeof(calculator_wsdlLocalDefinitions.policies.CalcBindingHeaderAuthSSL.envelopeVersion),
                },
            },
            WS_PROTECTION_LEVEL_SIGN_AND_ENCRYPT,
            { // securityPropertiesArray
                {
                    WS_SECURITY_PROPERTY_TRANSPORT_PROTECTION_LEVEL,
                    (void*)&calculator_wsdlLocalDefinitions.policies.CalcBindingHeaderAuthSSL.protectionLevel,
                    sizeof(calculator_wsdlLocalDefinitions.policies.CalcBindingHeaderAuthSSL.protectionLevel),
                },
            },
            {  // headerAuthBinding
                WS_HTTP_HEADER_AUTH_SCHEME_NEGOTIATE,
                {  // security binding properties
                    {
                        WS_SECURITY_BINDING_PROPERTY_HTTP_HEADER_AUTH_SCHEME,
                        (void*)&calculator_wsdlLocalDefinitions.policies.CalcBindingHeaderAuthSSL.headerAuthBinding.headerAuthentication,
                        sizeof(calculator_wsdlLocalDefinitions.policies.CalcBindingHeaderAuthSSL.headerAuthBinding.headerAuthentication),
                    },
                },  // security binding properties
            },  // headerAuthBinding
        },   // end of CalcBindingHeaderAuthSSL,
        {
            WS_ENCODING_XML_UTF8,
            WS_ADDRESSING_VERSION_TRANSPORT,
            WS_ENVELOPE_VERSION_SOAP_1_2,
            { // channelPropertiesArray
                {
                    WS_CHANNEL_PROPERTY_ENCODING,
                    (void*)&calculator_wsdlLocalDefinitions.policies.CalcBindingSSL.encoding,
                    sizeof(calculator_wsdlLocalDefinitions.policies.CalcBindingSSL.encoding),
                },
                {
                    WS_CHANNEL_PROPERTY_ADDRESSING_VERSION,
                    (void*)&calculator_wsdlLocalDefinitions.policies.CalcBindingSSL.addressingVersion,
                    sizeof(calculator_wsdlLocalDefinitions.policies.CalcBindingSSL.addressingVersion),
                },
                {
                    WS_CHANNEL_PROPERTY_ENVELOPE_VERSION,
                    (void*)&calculator_wsdlLocalDefinitions.policies.CalcBindingSSL.envelopeVersion,
                    sizeof(calculator_wsdlLocalDefinitions.policies.CalcBindingSSL.envelopeVersion),
                },
            },
            WS_PROTECTION_LEVEL_SIGN_AND_ENCRYPT,
            { // securityPropertiesArray
                {
                    WS_SECURITY_PROPERTY_TRANSPORT_PROTECTION_LEVEL,
                    (void*)&calculator_wsdlLocalDefinitions.policies.CalcBindingSSL.protectionLevel,
                    sizeof(calculator_wsdlLocalDefinitions.policies.CalcBindingSSL.protectionLevel),
                },
            },
        },   // end of CalcBindingSSL,
        {
            WS_ENCODING_XML_UTF8,
            WS_ADDRESSING_VERSION_TRANSPORT,
            WS_ENVELOPE_VERSION_SOAP_1_2,
            { // channelPropertiesArray
                {
                    WS_CHANNEL_PROPERTY_ENCODING,
                    (void*)&calculator_wsdlLocalDefinitions.policies.CalcBindingUnsecure.encoding,
                    sizeof(calculator_wsdlLocalDefinitions.policies.CalcBindingUnsecure.encoding),
                },
                {
                    WS_CHANNEL_PROPERTY_ADDRESSING_VERSION,
                    (void*)&calculator_wsdlLocalDefinitions.policies.CalcBindingUnsecure.addressingVersion,
                    sizeof(calculator_wsdlLocalDefinitions.policies.CalcBindingUnsecure.addressingVersion),
                },
                {
                    WS_CHANNEL_PROPERTY_ENVELOPE_VERSION,
                    (void*)&calculator_wsdlLocalDefinitions.policies.CalcBindingUnsecure.envelopeVersion,
                    sizeof(calculator_wsdlLocalDefinitions.policies.CalcBindingUnsecure.envelopeVersion),
                },
            },
        },   // end of CalcBindingUnsecure,
    }, // policies
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("EmptyRequest",&calculator_wsdlLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://calculator.example.org/",&calculator_wsdlLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("MultipurposeSingleIntegerResponse",&calculator_wsdlLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("result",&calculator_wsdlLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("BinaryOpRequest",&calculator_wsdlLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("first",&calculator_wsdlLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("second",&calculator_wsdlLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("OperationResponse",&calculator_wsdlLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("CloseServiceRequest",&calculator_wsdlLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("CloseServiceResponse",&calculator_wsdlLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("AdditionRequest",&calculator_wsdlLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("AdditionResponse",&calculator_wsdlLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("MultiplicationRequest",&calculator_wsdlLocalDefinitions.dictionary.dict, 12),
            WS_XML_STRING_DICTIONARY_VALUE("MultiplicationResponse",&calculator_wsdlLocalDefinitions.dictionary.dict, 13),
            WS_XML_STRING_DICTIONARY_VALUE("http://calculator.example.org/Add",&calculator_wsdlLocalDefinitions.dictionary.dict, 14),
            WS_XML_STRING_DICTIONARY_VALUE("http://calculator.example.org/Multiply",&calculator_wsdlLocalDefinitions.dictionary.dict, 15),
            WS_XML_STRING_DICTIONARY_VALUE("http://calculator.example.org/Close",&calculator_wsdlLocalDefinitions.dictionary.dict, 16),
        },  // end of xmlStrings
        
        {  // calculator_wsdldictionary
          // d24fb5ae-7b8b-510a-92e0-02be8b5bbeae 
        { 0xd24fb5ae, 0x7b8b, 0x510a, { 0x92, 0xe0, 0x02,0xbe, 0x8b, 0x5b, 0xbe, 0xae } },
        (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings,
        17,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of calculator_wsdlLocalDefinitions

const _calculator_wsdl calculator_wsdl =
{
    {  // globalTypes
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.EmptyRequestTypeName, // EmptyRequest
        (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.EmptyRequestTypeNamespace, // http://calculator.example.org/
        0,
        0,
        0,
        },   // end of struct description for EmptyRequest
        {
        sizeof(MultipurposeSingleIntegerResponse),
        __alignof(MultipurposeSingleIntegerResponse),
        (WS_FIELD_DESCRIPTION**)&calculator_wsdlLocalDefinitions.globalTypes.MultipurposeSingleIntegerResponsedescs.MultipurposeSingleIntegerResponseFields,
        WsCountOf(calculator_wsdlLocalDefinitions.globalTypes.MultipurposeSingleIntegerResponsedescs.MultipurposeSingleIntegerResponseFields),
        (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.MultipurposeSingleIntegerResponseTypeName, // MultipurposeSingleIntegerResponse
        (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.EmptyRequestTypeNamespace, // http://calculator.example.org/
        0,
        0,
        0,
        },   // end of struct description for MultipurposeSingleIntegerResponse
        {
        sizeof(BinaryOpRequest),
        __alignof(BinaryOpRequest),
        (WS_FIELD_DESCRIPTION**)&calculator_wsdlLocalDefinitions.globalTypes.BinaryOpRequestdescs.BinaryOpRequestFields,
        WsCountOf(calculator_wsdlLocalDefinitions.globalTypes.BinaryOpRequestdescs.BinaryOpRequestFields),
        (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestTypeName, // BinaryOpRequest
        (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.EmptyRequestTypeNamespace, // http://calculator.example.org/
        0,
        0,
        0,
        },   // end of struct description for BinaryOpRequest
        {
        sizeof(OperationResponse),
        __alignof(OperationResponse),
        (WS_FIELD_DESCRIPTION**)&calculator_wsdlLocalDefinitions.globalTypes.OperationResponsedescs.OperationResponseFields,
        WsCountOf(calculator_wsdlLocalDefinitions.globalTypes.OperationResponsedescs.OperationResponseFields),
        (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.OperationResponseTypeName, // OperationResponse
        (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.EmptyRequestTypeNamespace, // http://calculator.example.org/
        0,
        0,
        0,
        },   // end of struct description for OperationResponse
    },  // globalTypes
    {  // globalElements
        {
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.CloseServiceRequestTypeName, // CloseServiceRequest
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.EmptyRequestTypeNamespace, // http://calculator.example.org/
            WS_STRUCT_TYPE,
            (void*)&calculator_wsdl.globalTypes.EmptyRequest,
        },
        {
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.CloseServiceResponseTypeName, // CloseServiceResponse
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.EmptyRequestTypeNamespace, // http://calculator.example.org/
            WS_STRUCT_TYPE,
            (void*)&calculator_wsdl.globalTypes.MultipurposeSingleIntegerResponse,
        },
        {
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.AdditionRequestTypeName, // AdditionRequest
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.EmptyRequestTypeNamespace, // http://calculator.example.org/
            WS_STRUCT_TYPE,
            (void*)&calculator_wsdl.globalTypes.BinaryOpRequest,
        },
        {
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.AdditionResponseTypeName, // AdditionResponse
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.EmptyRequestTypeNamespace, // http://calculator.example.org/
            WS_STRUCT_TYPE,
            (void*)&calculator_wsdl.globalTypes.OperationResponse,
        },
        {
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.MultiplicationRequestTypeName, // MultiplicationRequest
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.EmptyRequestTypeNamespace, // http://calculator.example.org/
            WS_STRUCT_TYPE,
            (void*)&calculator_wsdl.globalTypes.BinaryOpRequest,
        },
        {
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.MultiplicationResponseTypeName, // MultiplicationResponse
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.EmptyRequestTypeNamespace, // http://calculator.example.org/
            WS_STRUCT_TYPE,
            (void*)&calculator_wsdl.globalTypes.OperationResponse,
        },
    },  // globalElements
    {  // messages
        {  // message description for AdditionRequestMessage
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.AdditionRequestMessageactionName, // http://calculator.example.org/Add
            (WS_ELEMENT_DESCRIPTION*)&calculator_wsdl.globalElements.AdditionRequest, 
        },    // message description for AdditionRequestMessage
        {  // message description for AdditionResponseMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&calculator_wsdl.globalElements.AdditionResponse, 
        },    // message description for AdditionResponseMessage
        {  // message description for MultiplicationRequestMessage
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.MultiplicationRequestMessageactionName, // http://calculator.example.org/Multiply
            (WS_ELEMENT_DESCRIPTION*)&calculator_wsdl.globalElements.MultiplicationRequest, 
        },    // message description for MultiplicationRequestMessage
        {  // message description for MultiplicationResponseMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&calculator_wsdl.globalElements.MultiplicationResponse, 
        },    // message description for MultiplicationResponseMessage
        {  // message description for CloseServiceRequestMessage
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.CloseServiceRequestMessageactionName, // http://calculator.example.org/Close
            (WS_ELEMENT_DESCRIPTION*)&calculator_wsdl.globalElements.CloseServiceRequest, 
        },    // message description for CloseServiceRequestMessage
        {  // message description for CloseServiceResponseMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&calculator_wsdl.globalElements.CloseServiceResponse, 
        },    // message description for CloseServiceResponseMessage
    },  // messages
    {  // contracts
        {  // CalcBindingHeaderAuthSSL
            3,
            (WS_OPERATION_DESCRIPTION**)calculator_wsdlLocalDefinitions.contracts.CalcBindingHeaderAuthSSL.operations,
        },  // end of CalcBindingHeaderAuthSSL
        {  // CalcBindingSSL
            3,
            (WS_OPERATION_DESCRIPTION**)calculator_wsdlLocalDefinitions.contracts.CalcBindingSSL.operations,
        },  // end of CalcBindingSSL
        {  // CalcBindingUnsecure
            3,
            (WS_OPERATION_DESCRIPTION**)calculator_wsdlLocalDefinitions.contracts.CalcBindingUnsecure.operations,
        },  // end of CalcBindingUnsecure
    },  // contracts
    {  // policies
        {  // template description for CalcBindingHeaderAuthSSL
            {  // channel properties
                (WS_CHANNEL_PROPERTY*)&calculator_wsdlLocalDefinitions.policies.CalcBindingHeaderAuthSSL.channelPropertiesArray,
                3,
            },
            {  // security properties
                (WS_SECURITY_PROPERTY*)&calculator_wsdlLocalDefinitions.policies.CalcBindingHeaderAuthSSL.securityPropertiesArray,
                1,
            },
            { // sslBinding
                { 
                    0,
                },
            },
            { // headerAuthBinding
                { 
                    (WS_SECURITY_BINDING_PROPERTY*)&calculator_wsdlLocalDefinitions.policies.CalcBindingHeaderAuthSSL.headerAuthBinding.securityBindingProperties,
                    1,
                },
            },
        },  // end of template description
        {  // template description for CalcBindingSSL
            {  // channel properties
                (WS_CHANNEL_PROPERTY*)&calculator_wsdlLocalDefinitions.policies.CalcBindingSSL.channelPropertiesArray,
                3,
            },
            {  // security properties
                (WS_SECURITY_PROPERTY*)&calculator_wsdlLocalDefinitions.policies.CalcBindingSSL.securityPropertiesArray,
                1,
            },
            { // sslBinding
                { 
                    0,
                },
            },
        },  // end of template description
        {  // template description for CalcBindingUnsecure
            {  // channel properties
                (WS_CHANNEL_PROPERTY*)&calculator_wsdlLocalDefinitions.policies.CalcBindingUnsecure.channelPropertiesArray,
                3,
            },
        },  // end of template description
    },  // policies
}; // end of _calculator_wsdl

HRESULT CalcBindingHeaderAuthSSL_CreateServiceEndpoint(
    _In_opt_ WS_HTTP_SSL_HEADER_AUTH_BINDING_TEMPLATE* templateValue,
    _In_opt_ CONST WS_STRING* address,
    _In_opt_ struct CalcBindingHeaderAuthSSLFunctionTable* functionTable,
    _In_opt_ WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    _In_reads_opt_(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    _In_ const ULONG endpointPropertyCount,
    _In_ WS_HEAP* heap,
    _Outptr_ WS_SERVICE_ENDPOINT** serviceEndpoint,
    _In_opt_ WS_ERROR* error)
{
    WS_SERVICE_CONTRACT serviceContract;
    serviceContract.contractDescription = &calculator_wsdl.contracts.CalcBindingHeaderAuthSSL;
    serviceContract.defaultMessageHandlerCallback = 0;
    serviceContract.methodTable = (const void*)functionTable;
    
    return WsCreateServiceEndpointFromTemplate(
        WS_CHANNEL_TYPE_REPLY,
        endpointProperties,
        endpointPropertyCount,
        address,
        &serviceContract,
        authorizationCallback,
        heap,
        WS_HTTP_SSL_HEADER_AUTH_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_SSL_HEADER_AUTH_BINDING_TEMPLATE),
        &calculator_wsdl.policies.CalcBindingHeaderAuthSSL,
        sizeof(calculator_wsdl.policies.CalcBindingHeaderAuthSSL),
        serviceEndpoint,
        error);
}

HRESULT CalcBindingSSL_CreateServiceEndpoint(
    _In_opt_ WS_HTTP_SSL_BINDING_TEMPLATE* templateValue,
    _In_opt_ CONST WS_STRING* address,
    _In_opt_ struct CalcBindingSSLFunctionTable* functionTable,
    _In_opt_ WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    _In_reads_opt_(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    _In_ const ULONG endpointPropertyCount,
    _In_ WS_HEAP* heap,
    _Outptr_ WS_SERVICE_ENDPOINT** serviceEndpoint,
    _In_opt_ WS_ERROR* error)
{
    WS_SERVICE_CONTRACT serviceContract;
    serviceContract.contractDescription = &calculator_wsdl.contracts.CalcBindingSSL;
    serviceContract.defaultMessageHandlerCallback = 0;
    serviceContract.methodTable = (const void*)functionTable;
    
    return WsCreateServiceEndpointFromTemplate(
        WS_CHANNEL_TYPE_REPLY,
        endpointProperties,
        endpointPropertyCount,
        address,
        &serviceContract,
        authorizationCallback,
        heap,
        WS_HTTP_SSL_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_SSL_BINDING_TEMPLATE),
        &calculator_wsdl.policies.CalcBindingSSL,
        sizeof(calculator_wsdl.policies.CalcBindingSSL),
        serviceEndpoint,
        error);
}

HRESULT CalcBindingUnsecure_CreateServiceEndpoint(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_opt_ CONST WS_STRING* address,
    _In_opt_ struct CalcBindingUnsecureFunctionTable* functionTable,
    _In_opt_ WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    _In_reads_opt_(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    _In_ const ULONG endpointPropertyCount,
    _In_ WS_HEAP* heap,
    _Outptr_ WS_SERVICE_ENDPOINT** serviceEndpoint,
    _In_opt_ WS_ERROR* error)
{
    WS_SERVICE_CONTRACT serviceContract;
    serviceContract.contractDescription = &calculator_wsdl.contracts.CalcBindingUnsecure;
    serviceContract.defaultMessageHandlerCallback = 0;
    serviceContract.methodTable = (const void*)functionTable;
    
    return WsCreateServiceEndpointFromTemplate(
        WS_CHANNEL_TYPE_REPLY,
        endpointProperties,
        endpointPropertyCount,
        address,
        &serviceContract,
        authorizationCallback,
        heap,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &calculator_wsdl.policies.CalcBindingUnsecure,
        sizeof(calculator_wsdl.policies.CalcBindingUnsecure),
        serviceEndpoint,
        error);
}
