
// File generated by Wsutil Compiler version 1.0095 
#include <WebServices.h>
#include "calculator.wsdl.h"

typedef struct _calculator_wsdlLocalDefinitions 
{
    struct  // global types
    {
        char unused;
        struct  // BinaryOpRequest
        {
            WS_FIELD_DESCRIPTION first;
            WS_FIELD_DESCRIPTION second;
            WS_FIELD_DESCRIPTION* BinaryOpRequestFields [2]; 
        } BinaryOpRequestdescs; // end of BinaryOpRequest
        struct  // OperationResponse
        {
            WS_FIELD_DESCRIPTION result;
            WS_FIELD_DESCRIPTION* OperationResponseFields [1]; 
        } OperationResponsedescs; // end of OperationResponse
    } globalTypes;  // end of global types
    struct  // messages
    {
        WS_MESSAGE_DESCRIPTION AdditionRequestMessage;
        WS_MESSAGE_DESCRIPTION AdditionResponseMessage;
        WS_MESSAGE_DESCRIPTION MultiplicationRequestMessage;
        WS_MESSAGE_DESCRIPTION MultiplicationResponseMessage;
    } messages;  // end of messages
    struct  // contracts
    {
        struct  // CalcBindingSSL
        {
            struct  // CalcBindingSSL_Add
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION CalcBindingSSL_Add;
            } CalcBindingSSL_Add;
            struct  // CalcBindingSSL_Multiplication
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION CalcBindingSSL_Multiplication;
            } CalcBindingSSL_Multiplication;
            WS_OPERATION_DESCRIPTION* operations[2];
            WS_CONTRACT_DESCRIPTION contractDesc;
        } CalcBindingSSL;
        struct  // CalcBindingUnsecure
        {
            struct  // CalcBindingUnsecure_Add
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION CalcBindingUnsecure_Add;
            } CalcBindingUnsecure_Add;
            struct  // CalcBindingUnsecure_Multiplication
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION CalcBindingUnsecure_Multiplication;
            } CalcBindingUnsecure_Multiplication;
            WS_OPERATION_DESCRIPTION* operations[2];
            WS_CONTRACT_DESCRIPTION contractDesc;
        } CalcBindingUnsecure;
    } contracts;  // endof contracts 
    struct  // policies
    {
        struct  // CalcBindingSSL
        {
            WS_ENCODING encoding;
            WS_ADDRESSING_VERSION addressingVersion;
            WS_ENVELOPE_VERSION envelopeVersion;
            WS_CHANNEL_PROPERTY channelPropertiesArray[3];
            WS_PROTECTION_LEVEL protectionLevel;
            WS_SECURITY_PROPERTY securityPropertiesArray[1];
        } CalcBindingSSL;
        struct  // CalcBindingUnsecure
        {
            WS_ENCODING encoding;
            WS_ADDRESSING_VERSION addressingVersion;
            WS_ENVELOPE_VERSION envelopeVersion;
            WS_CHANNEL_PROPERTY channelPropertiesArray[3];
        } CalcBindingUnsecure;
    } policies;
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING BinaryOpRequestTypeName;  // BinaryOpRequest
            WS_XML_STRING BinaryOpRequestTypeNamespace;  // http://calculator.example.org/
            WS_XML_STRING BinaryOpRequestfirstLocalName;  // first
            WS_XML_STRING BinaryOpRequestsecondLocalName;  // second
            WS_XML_STRING OperationResponseTypeName;  // OperationResponse
            WS_XML_STRING OperationResponseresultLocalName;  // result
            WS_XML_STRING AdditionRequestTypeName;  // AdditionRequest
            WS_XML_STRING AdditionResponseTypeName;  // AdditionResponse
            WS_XML_STRING MultiplicationRequestTypeName;  // MultiplicationRequest
            WS_XML_STRING MultiplicationResponseTypeName;  // MultiplicationResponse
            WS_XML_STRING AdditionRequestMessageactionName;  // http://calculator.example.org/Add
            WS_XML_STRING MultiplicationRequestMessageactionName;  // http://calculator.example.org/Multiply
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _calculator_wsdlLocalDefinitions;


typedef struct CalcBindingSSL_AddParamStruct 
{
    double* first;
    double* second;
    double* result;
} CalcBindingSSL_AddParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK CalcBindingSSL_AddOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    CalcBindingSSL_AddCallback _operation = (CalcBindingSSL_AddCallback)_callback;
    CalcBindingSSL_AddParamStruct *_stack =(CalcBindingSSL_AddParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->first),
        *(_stack->second),
        (_stack->result),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct CalcBindingSSL_MultiplicationParamStruct 
{
    double* first;
    double* second;
    double* result;
} CalcBindingSSL_MultiplicationParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK CalcBindingSSL_MultiplicationOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    CalcBindingSSL_MultiplicationCallback _operation = (CalcBindingSSL_MultiplicationCallback)_callback;
    CalcBindingSSL_MultiplicationParamStruct *_stack =(CalcBindingSSL_MultiplicationParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->first),
        *(_stack->second),
        (_stack->result),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct CalcBindingUnsecure_AddParamStruct 
{
    double* first;
    double* second;
    double* result;
} CalcBindingUnsecure_AddParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK CalcBindingUnsecure_AddOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    CalcBindingUnsecure_AddCallback _operation = (CalcBindingUnsecure_AddCallback)_callback;
    CalcBindingUnsecure_AddParamStruct *_stack =(CalcBindingUnsecure_AddParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->first),
        *(_stack->second),
        (_stack->result),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct CalcBindingUnsecure_MultiplicationParamStruct 
{
    double* first;
    double* second;
    double* result;
} CalcBindingUnsecure_MultiplicationParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK CalcBindingUnsecure_MultiplicationOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    CalcBindingUnsecure_MultiplicationCallback _operation = (CalcBindingUnsecure_MultiplicationCallback)_callback;
    CalcBindingUnsecure_MultiplicationParamStruct *_stack =(CalcBindingUnsecure_MultiplicationParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->first),
        *(_stack->second),
        (_stack->result),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif
const static _calculator_wsdlLocalDefinitions calculator_wsdlLocalDefinitions =
{
    { // global types
        0,
        {  // BinaryOpRequest
            {  // field description for first
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestfirstLocalName, // first
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestTypeNamespace, // http://calculator.example.org/
            WS_DOUBLE_TYPE,
            0,
            WsOffsetOf(BinaryOpRequest, first),
            0,
            0,
            0xffffffff
            },    // end of field description for first
            {  // field description for second
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestsecondLocalName, // second
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestTypeNamespace, // http://calculator.example.org/
            WS_DOUBLE_TYPE,
            0,
            WsOffsetOf(BinaryOpRequest, second),
            0,
            0,
            0xffffffff
            },    // end of field description for second
            {  // fields description for BinaryOpRequest
            (WS_FIELD_DESCRIPTION*)&calculator_wsdlLocalDefinitions.globalTypes.BinaryOpRequestdescs.first,
            (WS_FIELD_DESCRIPTION*)&calculator_wsdlLocalDefinitions.globalTypes.BinaryOpRequestdescs.second,
            },
        },    // BinaryOpRequest
        {  // OperationResponse
            {  // field description for result
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.OperationResponseresultLocalName, // result
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestTypeNamespace, // http://calculator.example.org/
            WS_DOUBLE_TYPE,
            0,
            WsOffsetOf(OperationResponse, result),
            0,
            0,
            0xffffffff
            },    // end of field description for result
            {  // fields description for OperationResponse
            (WS_FIELD_DESCRIPTION*)&calculator_wsdlLocalDefinitions.globalTypes.OperationResponsedescs.result,
            },
        },    // OperationResponse
    }, // end of global types
    {  // messages
        {  // message description for AdditionRequestMessage
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.AdditionRequestMessageactionName, // http://calculator.example.org/Add
            (WS_ELEMENT_DESCRIPTION*)&calculator_wsdl.globalElements.AdditionRequest, 
        },    // message description for AdditionRequestMessage
        {  // message description for AdditionResponseMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&calculator_wsdl.globalElements.AdditionResponse, 
        },    // message description for AdditionResponseMessage
        {  // message description for MultiplicationRequestMessage
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.MultiplicationRequestMessageactionName, // http://calculator.example.org/Multiply
            (WS_ELEMENT_DESCRIPTION*)&calculator_wsdl.globalElements.MultiplicationRequest, 
        },    // message description for MultiplicationRequestMessage
        {  // message description for MultiplicationResponseMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&calculator_wsdl.globalElements.MultiplicationResponse, 
        },    // message description for MultiplicationResponseMessage
    },  // end of messages 
    {  // contracts
        {  // CalcBindingSSL,
            {  // CalcBindingSSL_Add
                {  // parameter descriptions for CalcBindingSSL_Add
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for CalcBindingSSL_Add
                {  // operation description for CalcBindingSSL_Add
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.AdditionRequestMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.AdditionResponseMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)calculator_wsdlLocalDefinitions.contracts.CalcBindingSSL.CalcBindingSSL_Add.params,
                    CalcBindingSSL_AddOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for CalcBindingSSL_Add
            },  // CalcBindingSSL_Add
            {  // CalcBindingSSL_Multiplication
                {  // parameter descriptions for CalcBindingSSL_Multiplication
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for CalcBindingSSL_Multiplication
                {  // operation description for CalcBindingSSL_Multiplication
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.MultiplicationRequestMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.MultiplicationResponseMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)calculator_wsdlLocalDefinitions.contracts.CalcBindingSSL.CalcBindingSSL_Multiplication.params,
                    CalcBindingSSL_MultiplicationOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for CalcBindingSSL_Multiplication
            },  // CalcBindingSSL_Multiplication
            {  // array of operations for CalcBindingSSL
                (WS_OPERATION_DESCRIPTION*)&calculator_wsdlLocalDefinitions.contracts.CalcBindingSSL.CalcBindingSSL_Add.CalcBindingSSL_Add,
                (WS_OPERATION_DESCRIPTION*)&calculator_wsdlLocalDefinitions.contracts.CalcBindingSSL.CalcBindingSSL_Multiplication.CalcBindingSSL_Multiplication,
            },  // array of operations for CalcBindingSSL
            {  // contract description for CalcBindingSSL
            2,
            (WS_OPERATION_DESCRIPTION**)calculator_wsdlLocalDefinitions.contracts.CalcBindingSSL.operations,
            },  // end of contract description for CalcBindingSSL
        },  // CalcBindingSSL
        {  // CalcBindingUnsecure,
            {  // CalcBindingUnsecure_Add
                {  // parameter descriptions for CalcBindingUnsecure_Add
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for CalcBindingUnsecure_Add
                {  // operation description for CalcBindingUnsecure_Add
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.AdditionRequestMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.AdditionResponseMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)calculator_wsdlLocalDefinitions.contracts.CalcBindingUnsecure.CalcBindingUnsecure_Add.params,
                    CalcBindingUnsecure_AddOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for CalcBindingUnsecure_Add
            },  // CalcBindingUnsecure_Add
            {  // CalcBindingUnsecure_Multiplication
                {  // parameter descriptions for CalcBindingUnsecure_Multiplication
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for CalcBindingUnsecure_Multiplication
                {  // operation description for CalcBindingUnsecure_Multiplication
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.MultiplicationRequestMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&calculator_wsdl.messages.MultiplicationResponseMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)calculator_wsdlLocalDefinitions.contracts.CalcBindingUnsecure.CalcBindingUnsecure_Multiplication.params,
                    CalcBindingUnsecure_MultiplicationOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for CalcBindingUnsecure_Multiplication
            },  // CalcBindingUnsecure_Multiplication
            {  // array of operations for CalcBindingUnsecure
                (WS_OPERATION_DESCRIPTION*)&calculator_wsdlLocalDefinitions.contracts.CalcBindingUnsecure.CalcBindingUnsecure_Add.CalcBindingUnsecure_Add,
                (WS_OPERATION_DESCRIPTION*)&calculator_wsdlLocalDefinitions.contracts.CalcBindingUnsecure.CalcBindingUnsecure_Multiplication.CalcBindingUnsecure_Multiplication,
            },  // array of operations for CalcBindingUnsecure
            {  // contract description for CalcBindingUnsecure
            2,
            (WS_OPERATION_DESCRIPTION**)calculator_wsdlLocalDefinitions.contracts.CalcBindingUnsecure.operations,
            },  // end of contract description for CalcBindingUnsecure
        },  // CalcBindingUnsecure
    },  // end of contracts 
    {  // policies
        {
            WS_ENCODING_XML_UTF8,
            WS_ADDRESSING_VERSION_TRANSPORT,
            WS_ENVELOPE_VERSION_SOAP_1_2,
            { // channelPropertiesArray
                {
                    WS_CHANNEL_PROPERTY_ENCODING,
                    (void*)&calculator_wsdlLocalDefinitions.policies.CalcBindingSSL.encoding,
                    sizeof(calculator_wsdlLocalDefinitions.policies.CalcBindingSSL.encoding),
                },
                {
                    WS_CHANNEL_PROPERTY_ADDRESSING_VERSION,
                    (void*)&calculator_wsdlLocalDefinitions.policies.CalcBindingSSL.addressingVersion,
                    sizeof(calculator_wsdlLocalDefinitions.policies.CalcBindingSSL.addressingVersion),
                },
                {
                    WS_CHANNEL_PROPERTY_ENVELOPE_VERSION,
                    (void*)&calculator_wsdlLocalDefinitions.policies.CalcBindingSSL.envelopeVersion,
                    sizeof(calculator_wsdlLocalDefinitions.policies.CalcBindingSSL.envelopeVersion),
                },
            },
            WS_PROTECTION_LEVEL_SIGN_AND_ENCRYPT,
            { // securityPropertiesArray
                {
                    WS_SECURITY_PROPERTY_TRANSPORT_PROTECTION_LEVEL,
                    (void*)&calculator_wsdlLocalDefinitions.policies.CalcBindingSSL.protectionLevel,
                    sizeof(calculator_wsdlLocalDefinitions.policies.CalcBindingSSL.protectionLevel),
                },
            },
        },   // end of CalcBindingSSL,
        {
            WS_ENCODING_XML_UTF8,
            WS_ADDRESSING_VERSION_TRANSPORT,
            WS_ENVELOPE_VERSION_SOAP_1_2,
            { // channelPropertiesArray
                {
                    WS_CHANNEL_PROPERTY_ENCODING,
                    (void*)&calculator_wsdlLocalDefinitions.policies.CalcBindingUnsecure.encoding,
                    sizeof(calculator_wsdlLocalDefinitions.policies.CalcBindingUnsecure.encoding),
                },
                {
                    WS_CHANNEL_PROPERTY_ADDRESSING_VERSION,
                    (void*)&calculator_wsdlLocalDefinitions.policies.CalcBindingUnsecure.addressingVersion,
                    sizeof(calculator_wsdlLocalDefinitions.policies.CalcBindingUnsecure.addressingVersion),
                },
                {
                    WS_CHANNEL_PROPERTY_ENVELOPE_VERSION,
                    (void*)&calculator_wsdlLocalDefinitions.policies.CalcBindingUnsecure.envelopeVersion,
                    sizeof(calculator_wsdlLocalDefinitions.policies.CalcBindingUnsecure.envelopeVersion),
                },
            },
        },   // end of CalcBindingUnsecure,
    }, // policies
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("BinaryOpRequest",&calculator_wsdlLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://calculator.example.org/",&calculator_wsdlLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("first",&calculator_wsdlLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("second",&calculator_wsdlLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("OperationResponse",&calculator_wsdlLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("result",&calculator_wsdlLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("AdditionRequest",&calculator_wsdlLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("AdditionResponse",&calculator_wsdlLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("MultiplicationRequest",&calculator_wsdlLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("MultiplicationResponse",&calculator_wsdlLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("http://calculator.example.org/Add",&calculator_wsdlLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("http://calculator.example.org/Multiply",&calculator_wsdlLocalDefinitions.dictionary.dict, 11),
        },  // end of xmlStrings
        
        {  // calculator_wsdldictionary
          // f38970c3-47c9-460a-9677-0927062dc041 
        { 0xf38970c3, 0x47c9, 0x460a, { 0x96, 0x77, 0x09,0x27, 0x06, 0x2d, 0xc0, 0x41 } },
        (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings,
        12,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of calculator_wsdlLocalDefinitions

// Disable prefast warnings for the output parameters as their contract cannot be expressed in SAL.
#if (_MSC_VER >= 1400)
#pragma warning(push)
#endif
#pragma warning(disable: 6101 6054)

// operation: CalcBindingSSL_Add
HRESULT WINAPI CalcBindingSSL_Add(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ double first, 
    _In_ double second, 
    _Out_ double* result, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &first;
    _argList[1] = &second;
    _argList[2] = &result;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&calculator_wsdlLocalDefinitions.contracts.CalcBindingSSL.CalcBindingSSL_Add.CalcBindingSSL_Add,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: CalcBindingSSL_Multiplication
HRESULT WINAPI CalcBindingSSL_Multiplication(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ double first, 
    _In_ double second, 
    _Out_ double* result, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &first;
    _argList[1] = &second;
    _argList[2] = &result;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&calculator_wsdlLocalDefinitions.contracts.CalcBindingSSL.CalcBindingSSL_Multiplication.CalcBindingSSL_Multiplication,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: CalcBindingUnsecure_Add
HRESULT WINAPI CalcBindingUnsecure_Add(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ double first, 
    _In_ double second, 
    _Out_ double* result, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &first;
    _argList[1] = &second;
    _argList[2] = &result;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&calculator_wsdlLocalDefinitions.contracts.CalcBindingUnsecure.CalcBindingUnsecure_Add.CalcBindingUnsecure_Add,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: CalcBindingUnsecure_Multiplication
HRESULT WINAPI CalcBindingUnsecure_Multiplication(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ double first, 
    _In_ double second, 
    _Out_ double* result, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &first;
    _argList[1] = &second;
    _argList[2] = &result;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&calculator_wsdlLocalDefinitions.contracts.CalcBindingUnsecure.CalcBindingUnsecure_Multiplication.CalcBindingUnsecure_Multiplication,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}
#if (_MSC_VER >= 1400)
#pragma warning(pop)
#endif

const _calculator_wsdl calculator_wsdl =
{
    {  // globalTypes
        {
        sizeof(BinaryOpRequest),
        __alignof(BinaryOpRequest),
        (WS_FIELD_DESCRIPTION**)&calculator_wsdlLocalDefinitions.globalTypes.BinaryOpRequestdescs.BinaryOpRequestFields,
        WsCountOf(calculator_wsdlLocalDefinitions.globalTypes.BinaryOpRequestdescs.BinaryOpRequestFields),
        (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestTypeName, // BinaryOpRequest
        (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestTypeNamespace, // http://calculator.example.org/
        0,
        0,
        0,
        },   // end of struct description for BinaryOpRequest
        {
        sizeof(OperationResponse),
        __alignof(OperationResponse),
        (WS_FIELD_DESCRIPTION**)&calculator_wsdlLocalDefinitions.globalTypes.OperationResponsedescs.OperationResponseFields,
        WsCountOf(calculator_wsdlLocalDefinitions.globalTypes.OperationResponsedescs.OperationResponseFields),
        (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.OperationResponseTypeName, // OperationResponse
        (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestTypeNamespace, // http://calculator.example.org/
        0,
        0,
        0,
        },   // end of struct description for OperationResponse
    },  // globalTypes
    {  // globalElements
        {
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.AdditionRequestTypeName, // AdditionRequest
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestTypeNamespace, // http://calculator.example.org/
            WS_STRUCT_TYPE,
            (void*)&calculator_wsdl.globalTypes.BinaryOpRequest,
        },
        {
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.AdditionResponseTypeName, // AdditionResponse
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestTypeNamespace, // http://calculator.example.org/
            WS_STRUCT_TYPE,
            (void*)&calculator_wsdl.globalTypes.OperationResponse,
        },
        {
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.MultiplicationRequestTypeName, // MultiplicationRequest
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestTypeNamespace, // http://calculator.example.org/
            WS_STRUCT_TYPE,
            (void*)&calculator_wsdl.globalTypes.BinaryOpRequest,
        },
        {
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.MultiplicationResponseTypeName, // MultiplicationResponse
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestTypeNamespace, // http://calculator.example.org/
            WS_STRUCT_TYPE,
            (void*)&calculator_wsdl.globalTypes.OperationResponse,
        },
    },  // globalElements
    {  // messages
        {  // message description for AdditionRequestMessage
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.AdditionRequestMessageactionName, // http://calculator.example.org/Add
            (WS_ELEMENT_DESCRIPTION*)&calculator_wsdl.globalElements.AdditionRequest, 
        },    // message description for AdditionRequestMessage
        {  // message description for AdditionResponseMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&calculator_wsdl.globalElements.AdditionResponse, 
        },    // message description for AdditionResponseMessage
        {  // message description for MultiplicationRequestMessage
            (WS_XML_STRING*)&calculator_wsdlLocalDefinitions.dictionary.xmlStrings.MultiplicationRequestMessageactionName, // http://calculator.example.org/Multiply
            (WS_ELEMENT_DESCRIPTION*)&calculator_wsdl.globalElements.MultiplicationRequest, 
        },    // message description for MultiplicationRequestMessage
        {  // message description for MultiplicationResponseMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&calculator_wsdl.globalElements.MultiplicationResponse, 
        },    // message description for MultiplicationResponseMessage
    },  // messages
    {  // contracts
        {  // CalcBindingSSL
            2,
            (WS_OPERATION_DESCRIPTION**)calculator_wsdlLocalDefinitions.contracts.CalcBindingSSL.operations,
        },  // end of CalcBindingSSL
        {  // CalcBindingUnsecure
            2,
            (WS_OPERATION_DESCRIPTION**)calculator_wsdlLocalDefinitions.contracts.CalcBindingUnsecure.operations,
        },  // end of CalcBindingUnsecure
    },  // contracts
    {  // policies
        {  // template description for CalcBindingSSL
            {  // channel properties
                (WS_CHANNEL_PROPERTY*)&calculator_wsdlLocalDefinitions.policies.CalcBindingSSL.channelPropertiesArray,
                3,
            },
            {  // security properties
                (WS_SECURITY_PROPERTY*)&calculator_wsdlLocalDefinitions.policies.CalcBindingSSL.securityPropertiesArray,
                1,
            },
            { // sslBinding
                { 
                    0,
                },
            },
        },  // end of template description
        {  // template description for CalcBindingUnsecure
            {  // channel properties
                (WS_CHANNEL_PROPERTY*)&calculator_wsdlLocalDefinitions.policies.CalcBindingUnsecure.channelPropertiesArray,
                3,
            },
        },  // end of template description
    },  // policies
}; // end of _calculator_wsdl

HRESULT CalcBindingSSL_CreateServiceProxy(
    _In_opt_ WS_HTTP_SSL_BINDING_TEMPLATE* templateValue,
    _In_reads_opt_(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
    _In_ const ULONG proxyPropertyCount,
    _Outptr_ WS_SERVICE_PROXY** _serviceProxy,
    _In_opt_ WS_ERROR* error)
{
    return WsCreateServiceProxyFromTemplate(
        WS_CHANNEL_TYPE_REQUEST,
        proxyProperties,
        proxyPropertyCount,
        WS_HTTP_SSL_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_SSL_BINDING_TEMPLATE),
        &calculator_wsdl.policies.CalcBindingSSL,
        sizeof(calculator_wsdl.policies.CalcBindingSSL),
        _serviceProxy,
        error);
}

HRESULT CalcBindingSSL_CreateServiceEndpoint(
    _In_opt_ WS_HTTP_SSL_BINDING_TEMPLATE* templateValue,
    _In_opt_ CONST WS_STRING* address,
    _In_opt_ struct CalcBindingSSLFunctionTable* functionTable,
    _In_opt_ WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    _In_reads_opt_(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    _In_ const ULONG endpointPropertyCount,
    _In_ WS_HEAP* heap,
    _Outptr_ WS_SERVICE_ENDPOINT** serviceEndpoint,
    _In_opt_ WS_ERROR* error)
{
    WS_SERVICE_CONTRACT serviceContract;
    serviceContract.contractDescription = &calculator_wsdl.contracts.CalcBindingSSL;
    serviceContract.defaultMessageHandlerCallback = 0;
    serviceContract.methodTable = (const void*)functionTable;
    
    return WsCreateServiceEndpointFromTemplate(
        WS_CHANNEL_TYPE_REPLY,
        endpointProperties,
        endpointPropertyCount,
        address,
        &serviceContract,
        authorizationCallback,
        heap,
        WS_HTTP_SSL_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_SSL_BINDING_TEMPLATE),
        &calculator_wsdl.policies.CalcBindingSSL,
        sizeof(calculator_wsdl.policies.CalcBindingSSL),
        serviceEndpoint,
        error);
}

HRESULT CalcBindingUnsecure_CreateServiceProxy(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_reads_opt_(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
    _In_ const ULONG proxyPropertyCount,
    _Outptr_ WS_SERVICE_PROXY** _serviceProxy,
    _In_opt_ WS_ERROR* error)
{
    return WsCreateServiceProxyFromTemplate(
        WS_CHANNEL_TYPE_REQUEST,
        proxyProperties,
        proxyPropertyCount,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &calculator_wsdl.policies.CalcBindingUnsecure,
        sizeof(calculator_wsdl.policies.CalcBindingUnsecure),
        _serviceProxy,
        error);
}

HRESULT CalcBindingUnsecure_CreateServiceEndpoint(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_opt_ CONST WS_STRING* address,
    _In_opt_ struct CalcBindingUnsecureFunctionTable* functionTable,
    _In_opt_ WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    _In_reads_opt_(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    _In_ const ULONG endpointPropertyCount,
    _In_ WS_HEAP* heap,
    _Outptr_ WS_SERVICE_ENDPOINT** serviceEndpoint,
    _In_opt_ WS_ERROR* error)
{
    WS_SERVICE_CONTRACT serviceContract;
    serviceContract.contractDescription = &calculator_wsdl.contracts.CalcBindingUnsecure;
    serviceContract.defaultMessageHandlerCallback = 0;
    serviceContract.methodTable = (const void*)functionTable;
    
    return WsCreateServiceEndpointFromTemplate(
        WS_CHANNEL_TYPE_REPLY,
        endpointProperties,
        endpointPropertyCount,
        address,
        &serviceContract,
        authorizationCallback,
        heap,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &calculator_wsdl.policies.CalcBindingUnsecure,
        sizeof(calculator_wsdl.policies.CalcBindingUnsecure),
        serviceEndpoint,
        error);
}
