#ifndef RPC_H // header guard
#define RPC_H

#include <memory>
#include <string>
#include <vector>
#include <mutex>
#include <rpc.h>

namespace _3fd
{
    using std::string;

    namespace rpc
    {

        /// <summary>
        /// Enumerates the possible options for RPC transport.
        /// </summary>
        enum class ProtocolSequence { Local, TCP, UDP };

        class RpcServerImpl;

        /// <summary>
        /// Represents the RPC server that runs inside the application process.
        /// </summary>
        class RpcServer
        {
        private:

            static std::unique_ptr<RpcServerImpl> uniqueObject;

            static std::mutex singletonAccessMutex;

            RpcServer() {}

        public:

            ~RpcServer() {}

            static void Initialize(ProtocolSequence protSeq,
                                   const string &serviceClass,
                                   bool useActDirSec = true);

            static bool Start(const std::vector<RPC_IF_HANDLE> &interfaces);

            static bool Stop();

            static bool Resume();

            static bool Wait();

            static void Finalize() noexcept;
        };

        /// <summary>
        /// Implements an RPC client that provides an explicit binding handle
        /// to use as parameter for client stub code generated by the MIDL compiler.
        /// Client code is expected to derive from this class and call <see cref="RpcClient::GetBindingHandle"/>
        /// in order to obtain an explicit binding handle.
        /// </summary>
        class RpcClient
        {
        private:

            RPC_BINDING_HANDLE m_bindingHandle;

        protected:

            /// <summary>
            /// Gets the binding handle.
            /// </summary>
            /// <returns>The explicit binding handle expected as parameter for RPC.</returns>
            RPC_BINDING_HANDLE GetBindingHandle() const { return m_bindingHandle; }

        public:

            RpcClient(
                const string &intfUUID,
                ProtocolSequence protSeq,
                const string &destination,
                const string &endpoint
            );

            ~RpcClient();
        };

    }// end of namespace rpc
}// end of namespace _3fd

#endif // end of header guard
