
// File generated by Wsutil Compiler version 1.0095 
#include <WebServices.h>
#include "wsdl-example.wsdl.h"

typedef struct _wsdl_example_wsdlLocalDefinitions 
{
    struct  // global types
    {
        char unused;
        struct  // BinaryOpRequest
        {
            WS_FIELD_DESCRIPTION first;
            WS_FIELD_DESCRIPTION second;
            WS_FIELD_DESCRIPTION* BinaryOpRequestFields [2]; 
        } BinaryOpRequestdescs; // end of BinaryOpRequest
        struct  // OperationResponse
        {
            WS_FIELD_DESCRIPTION result;
            WS_FIELD_DESCRIPTION* OperationResponseFields [1]; 
        } OperationResponsedescs; // end of OperationResponse
    } globalTypes;  // end of global types
    struct  // messages
    {
        WS_MESSAGE_DESCRIPTION AdditionRequestMessage;
        WS_MESSAGE_DESCRIPTION AdditionResponseMessage;
    } messages;  // end of messages
    struct  // contracts
    {
        struct  // CalculatorBinding
        {
            struct  // CalculatorBinding_Add
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION CalculatorBinding_Add;
            } CalculatorBinding_Add;
            WS_OPERATION_DESCRIPTION* operations[1];
            WS_CONTRACT_DESCRIPTION contractDesc;
        } CalculatorBinding;
    } contracts;  // endof contracts 
    struct  // policies
    {
        struct  // CalculatorBinding
        {
            WS_ENCODING encoding;
            WS_ADDRESSING_VERSION addressingVersion;
            WS_ENVELOPE_VERSION envelopeVersion;
            WS_CHANNEL_PROPERTY channelPropertiesArray[3];
        } CalculatorBinding;
    } policies;
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING BinaryOpRequestTypeName;  // BinaryOpRequest
            WS_XML_STRING BinaryOpRequestTypeNamespace;  // http://calculator.example.org/
            WS_XML_STRING BinaryOpRequestfirstLocalName;  // first
            WS_XML_STRING BinaryOpRequestsecondLocalName;  // second
            WS_XML_STRING OperationResponseTypeName;  // OperationResponse
            WS_XML_STRING OperationResponseresultLocalName;  // result
            WS_XML_STRING AdditionRequestTypeName;  // AdditionRequest
            WS_XML_STRING AdditionResponseTypeName;  // AdditionResponse
            WS_XML_STRING AdditionRequestMessageactionName;  // http://calculator.example.org/Add
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _wsdl_example_wsdlLocalDefinitions;


typedef struct CalculatorBinding_AddParamStruct 
{
    double* first;
    double* second;
    double* result;
} CalculatorBinding_AddParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK CalculatorBinding_AddOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    CalculatorBinding_AddCallback _operation = (CalculatorBinding_AddCallback)_callback;
    CalculatorBinding_AddParamStruct *_stack =(CalculatorBinding_AddParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->first),
        *(_stack->second),
        (_stack->result),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif
const static _wsdl_example_wsdlLocalDefinitions wsdl_example_wsdlLocalDefinitions =
{
    { // global types
        0,
        {  // BinaryOpRequest
            {  // field description for first
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&wsdl_example_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestfirstLocalName, // first
            (WS_XML_STRING*)&wsdl_example_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestTypeNamespace, // http://calculator.example.org/
            WS_DOUBLE_TYPE,
            0,
            WsOffsetOf(BinaryOpRequest, first),
            0,
            0,
            0xffffffff
            },    // end of field description for first
            {  // field description for second
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&wsdl_example_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestsecondLocalName, // second
            (WS_XML_STRING*)&wsdl_example_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestTypeNamespace, // http://calculator.example.org/
            WS_DOUBLE_TYPE,
            0,
            WsOffsetOf(BinaryOpRequest, second),
            0,
            0,
            0xffffffff
            },    // end of field description for second
            {  // fields description for BinaryOpRequest
            (WS_FIELD_DESCRIPTION*)&wsdl_example_wsdlLocalDefinitions.globalTypes.BinaryOpRequestdescs.first,
            (WS_FIELD_DESCRIPTION*)&wsdl_example_wsdlLocalDefinitions.globalTypes.BinaryOpRequestdescs.second,
            },
        },    // BinaryOpRequest
        {  // OperationResponse
            {  // field description for result
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&wsdl_example_wsdlLocalDefinitions.dictionary.xmlStrings.OperationResponseresultLocalName, // result
            (WS_XML_STRING*)&wsdl_example_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestTypeNamespace, // http://calculator.example.org/
            WS_DOUBLE_TYPE,
            0,
            WsOffsetOf(OperationResponse, result),
            0,
            0,
            0xffffffff
            },    // end of field description for result
            {  // fields description for OperationResponse
            (WS_FIELD_DESCRIPTION*)&wsdl_example_wsdlLocalDefinitions.globalTypes.OperationResponsedescs.result,
            },
        },    // OperationResponse
    }, // end of global types
    {  // messages
        {  // message description for AdditionRequestMessage
            (WS_XML_STRING*)&wsdl_example_wsdlLocalDefinitions.dictionary.xmlStrings.AdditionRequestMessageactionName, // http://calculator.example.org/Add
            (WS_ELEMENT_DESCRIPTION*)&wsdl_example_wsdl.globalElements.AdditionRequest, 
        },    // message description for AdditionRequestMessage
        {  // message description for AdditionResponseMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&wsdl_example_wsdl.globalElements.AdditionResponse, 
        },    // message description for AdditionResponseMessage
    },  // end of messages 
    {  // contracts
        {  // CalculatorBinding,
            {  // CalculatorBinding_Add
                {  // parameter descriptions for CalculatorBinding_Add
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for CalculatorBinding_Add
                {  // operation description for CalculatorBinding_Add
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&wsdl_example_wsdl.messages.AdditionRequestMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&wsdl_example_wsdl.messages.AdditionResponseMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)wsdl_example_wsdlLocalDefinitions.contracts.CalculatorBinding.CalculatorBinding_Add.params,
                    CalculatorBinding_AddOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for CalculatorBinding_Add
            },  // CalculatorBinding_Add
            {  // array of operations for CalculatorBinding
                (WS_OPERATION_DESCRIPTION*)&wsdl_example_wsdlLocalDefinitions.contracts.CalculatorBinding.CalculatorBinding_Add.CalculatorBinding_Add,
            },  // array of operations for CalculatorBinding
            {  // contract description for CalculatorBinding
            1,
            (WS_OPERATION_DESCRIPTION**)wsdl_example_wsdlLocalDefinitions.contracts.CalculatorBinding.operations,
            },  // end of contract description for CalculatorBinding
        },  // CalculatorBinding
    },  // end of contracts 
    {  // policies
        {
            WS_ENCODING_XML_UTF8,
            WS_ADDRESSING_VERSION_TRANSPORT,
            WS_ENVELOPE_VERSION_SOAP_1_1,
            { // channelPropertiesArray
                {
                    WS_CHANNEL_PROPERTY_ENCODING,
                    (void*)&wsdl_example_wsdlLocalDefinitions.policies.CalculatorBinding.encoding,
                    sizeof(wsdl_example_wsdlLocalDefinitions.policies.CalculatorBinding.encoding),
                },
                {
                    WS_CHANNEL_PROPERTY_ADDRESSING_VERSION,
                    (void*)&wsdl_example_wsdlLocalDefinitions.policies.CalculatorBinding.addressingVersion,
                    sizeof(wsdl_example_wsdlLocalDefinitions.policies.CalculatorBinding.addressingVersion),
                },
                {
                    WS_CHANNEL_PROPERTY_ENVELOPE_VERSION,
                    (void*)&wsdl_example_wsdlLocalDefinitions.policies.CalculatorBinding.envelopeVersion,
                    sizeof(wsdl_example_wsdlLocalDefinitions.policies.CalculatorBinding.envelopeVersion),
                },
            },
        },   // end of CalculatorBinding,
    }, // policies
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("BinaryOpRequest",&wsdl_example_wsdlLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://calculator.example.org/",&wsdl_example_wsdlLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("first",&wsdl_example_wsdlLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("second",&wsdl_example_wsdlLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("OperationResponse",&wsdl_example_wsdlLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("result",&wsdl_example_wsdlLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("AdditionRequest",&wsdl_example_wsdlLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("AdditionResponse",&wsdl_example_wsdlLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("http://calculator.example.org/Add",&wsdl_example_wsdlLocalDefinitions.dictionary.dict, 8),
        },  // end of xmlStrings
        
        {  // wsdl_example_wsdldictionary
          // 7e182680-b26d-4aa3-8925-7590ae638fe8 
        { 0x7e182680, 0xb26d, 0x4aa3, { 0x89, 0x25, 0x75,0x90, 0xae, 0x63, 0x8f, 0xe8 } },
        (WS_XML_STRING*)&wsdl_example_wsdlLocalDefinitions.dictionary.xmlStrings,
        9,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of wsdl_example_wsdlLocalDefinitions

// Disable prefast warnings for the output parameters as their contract cannot be expressed in SAL.
#if (_MSC_VER >= 1400)
#pragma warning(push)
#endif
#pragma warning(disable: 6101 6054)

// operation: CalculatorBinding_Add
HRESULT WINAPI CalculatorBinding_Add(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ double first, 
    _In_ double second, 
    _Out_ double* result, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &first;
    _argList[1] = &second;
    _argList[2] = &result;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&wsdl_example_wsdlLocalDefinitions.contracts.CalculatorBinding.CalculatorBinding_Add.CalculatorBinding_Add,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}
#if (_MSC_VER >= 1400)
#pragma warning(pop)
#endif

const _wsdl_example_wsdl wsdl_example_wsdl =
{
    {  // globalTypes
        {
        sizeof(BinaryOpRequest),
        __alignof(BinaryOpRequest),
        (WS_FIELD_DESCRIPTION**)&wsdl_example_wsdlLocalDefinitions.globalTypes.BinaryOpRequestdescs.BinaryOpRequestFields,
        WsCountOf(wsdl_example_wsdlLocalDefinitions.globalTypes.BinaryOpRequestdescs.BinaryOpRequestFields),
        (WS_XML_STRING*)&wsdl_example_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestTypeName, // BinaryOpRequest
        (WS_XML_STRING*)&wsdl_example_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestTypeNamespace, // http://calculator.example.org/
        0,
        0,
        0,
        },   // end of struct description for BinaryOpRequest
        {
        sizeof(OperationResponse),
        __alignof(OperationResponse),
        (WS_FIELD_DESCRIPTION**)&wsdl_example_wsdlLocalDefinitions.globalTypes.OperationResponsedescs.OperationResponseFields,
        WsCountOf(wsdl_example_wsdlLocalDefinitions.globalTypes.OperationResponsedescs.OperationResponseFields),
        (WS_XML_STRING*)&wsdl_example_wsdlLocalDefinitions.dictionary.xmlStrings.OperationResponseTypeName, // OperationResponse
        (WS_XML_STRING*)&wsdl_example_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestTypeNamespace, // http://calculator.example.org/
        0,
        0,
        0,
        },   // end of struct description for OperationResponse
    },  // globalTypes
    {  // globalElements
        {
            (WS_XML_STRING*)&wsdl_example_wsdlLocalDefinitions.dictionary.xmlStrings.AdditionRequestTypeName, // AdditionRequest
            (WS_XML_STRING*)&wsdl_example_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestTypeNamespace, // http://calculator.example.org/
            WS_STRUCT_TYPE,
            (void*)&wsdl_example_wsdl.globalTypes.BinaryOpRequest,
        },
        {
            (WS_XML_STRING*)&wsdl_example_wsdlLocalDefinitions.dictionary.xmlStrings.AdditionResponseTypeName, // AdditionResponse
            (WS_XML_STRING*)&wsdl_example_wsdlLocalDefinitions.dictionary.xmlStrings.BinaryOpRequestTypeNamespace, // http://calculator.example.org/
            WS_STRUCT_TYPE,
            (void*)&wsdl_example_wsdl.globalTypes.OperationResponse,
        },
    },  // globalElements
    {  // messages
        {  // message description for AdditionRequestMessage
            (WS_XML_STRING*)&wsdl_example_wsdlLocalDefinitions.dictionary.xmlStrings.AdditionRequestMessageactionName, // http://calculator.example.org/Add
            (WS_ELEMENT_DESCRIPTION*)&wsdl_example_wsdl.globalElements.AdditionRequest, 
        },    // message description for AdditionRequestMessage
        {  // message description for AdditionResponseMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&wsdl_example_wsdl.globalElements.AdditionResponse, 
        },    // message description for AdditionResponseMessage
    },  // messages
    {  // contracts
        {  // CalculatorBinding
            1,
            (WS_OPERATION_DESCRIPTION**)wsdl_example_wsdlLocalDefinitions.contracts.CalculatorBinding.operations,
        },  // end of CalculatorBinding
    },  // contracts
    {  // policies
        {  // template description for CalculatorBinding
            {  // channel properties
                (WS_CHANNEL_PROPERTY*)&wsdl_example_wsdlLocalDefinitions.policies.CalculatorBinding.channelPropertiesArray,
                3,
            },
        },  // end of template description
    },  // policies
}; // end of _wsdl_example_wsdl

HRESULT CalculatorBinding_CreateServiceProxy(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_reads_opt_(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
    _In_ const ULONG proxyPropertyCount,
    _Outptr_ WS_SERVICE_PROXY** _serviceProxy,
    _In_opt_ WS_ERROR* error)
{
    return WsCreateServiceProxyFromTemplate(
        WS_CHANNEL_TYPE_REQUEST,
        proxyProperties,
        proxyPropertyCount,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &wsdl_example_wsdl.policies.CalculatorBinding,
        sizeof(wsdl_example_wsdl.policies.CalculatorBinding),
        _serviceProxy,
        error);
}

HRESULT CalculatorBinding_CreateServiceEndpoint(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_opt_ CONST WS_STRING* address,
    _In_opt_ struct CalculatorBindingFunctionTable* functionTable,
    _In_opt_ WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    _In_reads_opt_(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    _In_ const ULONG endpointPropertyCount,
    _In_ WS_HEAP* heap,
    _Outptr_ WS_SERVICE_ENDPOINT** serviceEndpoint,
    _In_opt_ WS_ERROR* error)
{
    WS_SERVICE_CONTRACT serviceContract;
    serviceContract.contractDescription = &wsdl_example_wsdl.contracts.CalculatorBinding;
    serviceContract.defaultMessageHandlerCallback = 0;
    serviceContract.methodTable = (const void*)functionTable;
    
    return WsCreateServiceEndpointFromTemplate(
        WS_CHANNEL_TYPE_REPLY,
        endpointProperties,
        endpointPropertyCount,
        address,
        &serviceContract,
        authorizationCallback,
        heap,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &wsdl_example_wsdl.policies.CalculatorBinding,
        sizeof(wsdl_example_wsdl.policies.CalculatorBinding),
        serviceEndpoint,
        error);
}
