//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::ImageTranscoderApp::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}


/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class ImageTranscoderApp::MainPage::MainPage_obj15_Bindings 
    : public ::XamlBindingInfo::ReferenceTypeXamlBindings<::ImageTranscoderApp::FileListItem>
{
public:
    MainPage_obj15_Bindings()
    {
    }

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 16:
                this->obj16 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
                break;
            case 17:
                this->obj17 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 18:
                this->obj18 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
        }
    }

    void ResetTemplate()
    {
    }

    int ProcessBindings(::Windows::UI::Xaml::Controls::ContainerContentChangingEventArgs^ args)
    {
        int nextPhase = -1;
        switch(args->Phase)
        {
            case 0:
                nextPhase = -1;
                this->SetDataRoot(static_cast<::ImageTranscoderApp::FileListItem^>(args->Item));
                if (this->_dataContextChangedToken.Value != 0)
                {
                    safe_cast<::Windows::UI::Xaml::FrameworkElement^>(args->ItemContainer->ContentTemplateRoot)->DataContextChanged -= this->_dataContextChangedToken;
                    this->_dataContextChangedToken.Value = 0;
                }
                this->_isInitialized = true;
                break;
        }
        this->Update_((::ImageTranscoderApp::FileListItem^) args->Item, (1 << args->Phase));
        return nextPhase;
    }
private:
    // Fields for each control that has bindings.
    ::Windows::UI::Xaml::Controls::Image^ obj16;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj17;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj18;

    // Update methods for each path node used in binding steps.
    void Update_(::ImageTranscoderApp::FileListItem^ obj, int phase)
    {
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_Thumbnail(obj->Thumbnail, phase);
                this->Update_FileExtension(obj->FileExtension, phase);
                this->Update_Description(obj->Description, phase);
            }
        }
    }
    void Update_Thumbnail(::Windows::UI::Xaml::Media::Imaging::BitmapImage^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_Image_Source(this->obj16, obj, nullptr);
        }
    }
    void Update_FileExtension(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj17, obj, nullptr);
        }
    }
    void Update_Description(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj18, obj, nullptr);
        }
    }
};

/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class ImageTranscoderApp::MainPage::MainPage_obj1_Bindings 
    : public ::XamlBindingInfo::ReferenceTypeXamlBindings<::ImageTranscoderApp::MainPage>
{
public:
    MainPage_obj1_Bindings()
    {
    }

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 12:
                this->obj12 = safe_cast<::Windows::UI::Xaml::Controls::ListView^>(__target);
                break;
        }
    }
private:
    // Fields for each control that has bindings.
    ::Windows::UI::Xaml::Controls::ListView^ obj12;

    // Update methods for each path node used in binding steps.
    void Update_(::ImageTranscoderApp::MainPage^ obj, int phase)
    {
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_InputImages(obj->InputImages, phase);
            }
        }
    }
    void Update_InputImages(::Windows::Foundation::Collections::IObservableVector<::ImageTranscoderApp::FileListItem^>^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_ItemsControl_ItemsSource(this->obj12, obj, nullptr);
        }
    }
};

void ::ImageTranscoderApp::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->wideState = safe_cast<::Windows::UI::Xaml::VisualState^>(__target);
        }
        break;
    case 3:
        {
            this->narrowState = safe_cast<::Windows::UI::Xaml::VisualState^>(__target);
        }
        break;
    case 4:
        {
            this->LayoutRoot = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 5:
        {
            this->titleTxtBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 6:
        {
            this->ContentRoot = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 7:
        {
            this->CommandPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
        }
        break;
    case 8:
        {
            this->startButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->startButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ImageTranscoderApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::OnClickStartButton);
        }
        break;
    case 9:
        {
            this->qualitySlider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
        }
        break;
    case 10:
        {
            this->toJxrCheckBox = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(__target);
        }
        break;
    case 11:
        {
            this->waitingRing = safe_cast<::Windows::UI::Xaml::Controls::ProgressRing^>(__target);
        }
        break;
    case 12:
        {
            this->filesListView = safe_cast<::Windows::UI::Xaml::Controls::ListView^>(__target);
        }
        break;
    case 13:
        {
            this->selectImagesButton = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(this->selectImagesButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ImageTranscoderApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::OnClickSelectImagesButton);
        }
        break;
    case 14:
        {
            this->clearSelImagesButton = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(this->clearSelImagesButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ImageTranscoderApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::OnClickClearSelImagesButton);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::ImageTranscoderApp::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    ::XamlBindingInfo::XamlBindings^ bindings = nullptr;
    switch (__connectionId)
    {
        case 1:
            {
                ::Windows::UI::Xaml::Controls::Page^ element1 = safe_cast<::Windows::UI::Xaml::Controls::Page^>(__target);
                MainPage_obj1_Bindings* objBindings = new MainPage_obj1_Bindings();
                objBindings->SetDataRoot(this);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                this->Bindings = bindings;
                element1->Loading += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Platform::Object^>(bindings, &::XamlBindingInfo::XamlBindings::Loading);
            }
            break;
        case 15:
            {
                ::Windows::UI::Xaml::Controls::StackPanel^ element15 = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
                MainPage_obj15_Bindings* objBindings = new MainPage_obj15_Bindings();
                objBindings->SetDataRoot(element15->DataContext);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                bindings->SubscribeForDataContextChanged(element15);
                ::Windows::UI::Xaml::DataTemplate::SetExtensionInstance(element15, bindings);
            }
            break;
    }
    return bindings;
}

#pragma warning(pop)


