[
    uuid(ba209999-0c6c-11d2-97cf-00c04f8eea45),
    version(1.0)
]
interface AcmeTesting
{
    #define STRBUFSIZE 256

    typedef struct pair
    {
        int left;
        int right;
    } pair;

    void Invert([in, out] pair *onePair);

    void Operate([in] double left, [in] double right, [out] double *result);

    void ChangeCase([in, string] char *input, [out, string, size_is(STRBUFSIZE)] char *output);

    void WriteOnStorage(void);

    unsigned long Shutdown(void);
}
